### ISSUE TITLE
Improve Support and Feedback tab

### ISSUE THREAD

**Issue by JT-39** [dfe-analytical-services/dfeshiny#54]
## Is your feature request related to a problem? Please describe.

I would like more control over the `Support and Feedback` tab. At the moment it is quite tailored towards EES publications and less so for other types of dashboards.

## Describe the solution you'd like

- [x] An option to write your own text under the `Find more information on the data` subheading.
- [x] If possible further flexibility to also include other text and subheadings, such as a future development plan, update/version log table, etc..

Other improvements:

- [x] Could use the new `dfeshiny::external_link()` for links on the page so that they open in new tabs (I think especially important for the feedback form where people are likely to want to look back at an issue in the app whilst filling out the form).
- [x] Full stops after `feedback form` and `please contact us at youremail@gov.uk` .

## Describe alternatives you've considered

Could copy and paste the `dfeshiny::support_panel()` function into own repo and edit it that way.

## Additional context

Full stops:

<img width="901" alt="image" src="https://github.com/user-attachments/assets/e543e693-a7e6-4ff2-9e28-76b5379c479c">

<br>
<br>
<br>
<br>

Example of a tool update/ version log:

<img width="1119" alt="image" src="https://github.com/user-attachments/assets/b73ffb36-0111-459a-907d-b54b629f9bc0">

**Comment by cjrace** [comment]
I think #52 has done the moving over to `external_link()` part of this already?

Fully agree with the rest of it though, it would be better to make this more flexible so it can be used in more use cases, it's a bit too restrictive currently. Would be able to open it up to accept additional html tags under some of those headers so that if you wanted to you could add any content necessary in the right places. 

Would recommend making use of inbuilt stuff in GitHub where possible - like raising bugs, issue tracking, versioning releases to the dashboard etc, though all could be linked from or added into this page.

**Comment by JT-39** [comment]
Ahh yep, [#52](https://github.com/dfe-analytical-services/dfeshiny/pull/52) has done this. Needed to update `{dfeshiny}`.

Yeah that solution sounds great. I like the idea of linking specifically (and directly) to the issues page on GitHub.

Ooo okay, not sure if I've come across versioning releases to dashboards.

**Comment by mzayeddfe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [improve support and feedback tab](https://trello.com/c/ccTQYcLj/1842-improve-support-and-feedback-tab)
