### ISSUE TITLE
DfE header function

### ISSUE THREAD

**Issue by rmbielby** [dfe-analytical-services/dfeshiny#57]
## Is your feature request related to a problem? Please describe.
At the moment we produce headers in dashboard using the [shinyGovstyle function](https://moj-analytical-services.github.io/shinyGovstyle/reference/header.html), which requires us to specifically add the preferred DfE logo into all repos. That logo's just changed and it would've been super useful to have had the logo in dfeshiny and all the dashboards just use a dfeshiny header function that creates the official header as we need it and with the up to date DfE logo.

## Describe the solution you'd like
dfeshiny::header() replaces shinyGovstyle::header() and sets the logo to the standard DfE logo as recorded in the package.

## Describe alternatives you've considered
Carry on leaving analysts to create the header using shinyGovstyle, but this means more work long term in terms of making sure all dashboards consistently use the right logo.

## Additional context
- Logos are available on [dropbox](https://www.dropbox.com/scl/fo/6d1rrhybje68u2zd0053m/ANtEQUG-4GzvgMQjILKPlVI?rlkey=v6zg12t7tgvsl9hmxe17z0rda&e=1&dl=0)
- And here's the code for the existing shinyGovstyle function that I think we'd want to adapt: 
[header.R](https://github.com/moj-analytical-services/shinyGovstyle/blob/v0.1.0/R/header.R)

**Comment by cjrace** [comment]
Would we want to create a dfe wrapper around the `shinyGovstyle::header()` function to just set a default logo for DfE and accept a list of other arguments to pass into the shinyGovstyle function? Feels better to keep the connection with shinyGovstyle rather than duplicate and veer away from that.

Also, I'm assuming we could put the image in the www folder and it would be available once the package is installed in the same way the CSS can be due to the zzz.R on load things we have.

**Comment by mzayeddfe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [dfeshiny::header()](https://trello.com/c/tsAMXCST/1897-dfeshinyheader)
